### ISSUE TITLE
wavelet_tiling in the python wrapper doesn't work for the wavelet coefficients

### ISSUE THREAD

**Issue by paddyroddy** [astro-informatics/s2let#11]
I'm trying to recreate the `matlab` demo https://github.com/astro-informatics/src_s2let/blob/master/src/main/matlab/s2let_demo5.m and using the implementation of `wavelet_tiling` already in the `pys2let.pyx` file. However, the `psi_lm` appear to all be zero. I cannot run the `matlab` version but I assume this is not meant to be the case.

![image](https://user-images.githubusercontent.com/15052188/89024884-c290c000-d31d-11ea-955c-5665afb56d9e.png)

**Comment by auggiemarignier** [comment]
@paddyroddy I think the minimum value of N should be 1 and not 0.  N=1 corresponds to axisymmetric wavelets (see https://arxiv.org/pdf/1608.00553.pdf start of section IV.A), and in that case the psi_lm is not all zero.  I haven't checked that the `matlab` code works with N=0

**Comment by paddyroddy** [comment]
I've tried `N>=1` and that works as expected - but you can see my confusion from that MATLAB demo (which I assume works?!). Thanks.

I'll close this now although would be good if that MATLAB demo was checked
