### ISSUE TITLE
pip installable

### ISSUE THREAD

**Issue by paddyroddy** [astro-informatics/s2let#17]
Not being pip installable is a barrier for people using it. Not sure how much work this would involve.

@mdavezac how much work was involved with ssht?

**Comment by mdavezac** [comment]
It depends on the dependencies. I've setup [conan](https://conan.io/) packages for [ssht](https://bintray.com/beta/#/mdavezac/AstroFizz?tab=packages) but not so3. I think the other dependencies should be there.
So the steps would be:

1. add conan to so3's CMake build, possibly using ssht for inspiration and using the [ssht package](https://gitlab.com/mdavezac-conan/ssht)  as a dependency
1. add a conan package for so3, possibly using the [ssht package](https://gitlab.com/mdavezac-conan/ssht)  for inspiration
1. add conan to s2let's CMake build
1. add [scikit-build](https://scikit-build.readthedocs.io/en/latest/) setup for the python bit, possibly using ssht as inspiration

It's not difficult but there is a fair amount of learning for someone who has not seen these technologies. I would estimate it should take about a week for a newbie. Probably 2-3 days for someone who has dabbled with this stack before.

**Comment by mdavezac** [comment]
done

**Comment by paddyroddy** [comment]
great work!
