### ISSUE TITLE
Moving default branch to main.

### ISSUE THREAD

**Issue by mdavezac** [astro-informatics/s2let#24]
@paddyroddy, @auggiemarignier, the default branch is now main

**Comment by mdavezac** [comment]
master no longer exists.

**Comment by paddyroddy** [comment]
what is this madness 😛

**Comment by jasonmcewen** [comment]
Please see, e.g., https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by paddyroddy** [comment]
That's a good initiative
