### ISSUE TITLE
New build system failing

### ISSUE THREAD

**Issue by auggiemarignier** [astro-informatics/s2let#26]
I've tried doing `pip install` both from pypi and in a local copy and get the following error during the `conan install` step.  The same thing happens when running `cmake` as in the README.  It seems to be an issue when building `so3`, and I have tried the new build system for `so3` but got the same error when it was trying to install `ssht`.  Not sure if this is an issue with the code or just my conan profile but I'm not familiar enough with conan to tell
![Screenshot 2020-09-22 at 13 32 01](https://user-images.githubusercontent.com/42379892/93885240-d92f1400-fcdb-11ea-809a-81f3c947945e.png)

**Comment by mdavezac** [comment]
For now, please set compiler.libcxx following https://docs.conan.io/en/latest/howtos/manage_gcc_abi.html. I think I can correct this on the next update.

**Comment by mdavezac** [comment]
You can also delete the directory ~/.conan and run "conan profile new default --detect"

**Comment by auggiemarignier** [comment]
making a new conan profile worked.  must've been another one of the clang vs gcc issues..

**Comment by mdavezac** [comment]
Thanks @auggiemarignier. It should be fixed in #27 and on pypi now.
